"""外部流水明细数据适配器

此模块负责将外部流水明细数据直接集成到输出JSON中。
外部数据格式保持原样，不做额外转换。
"""
from typing import Any, Dict, Optional


def inject_external_transactions_to_output(
    output_data: Dict[str, Any],
    external_data: Dict[str, Any]
) -> Dict[str, Any]:
    """
    将外部流水明细数据注入到输出JSON中。
    
    直接使用外部数据格式，不做任何转换或增加额外信息。
    
    Args:
        output_data: 当前输出的JSON数据（包含metadata等）
        external_data: 外部流水明细数据
        
    Returns:
        合并后的完整JSON数据
    """
    # 直接将外部数据的pages结构添加到输出
    # 保持外部数据的原始格式和字段名称
    if "structured_data" not in output_data:
        output_data["structured_data"] = {}
    
    if "account_summary" not in output_data["structured_data"]:
        output_data["structured_data"]["account_summary"] = {}
    
    # 使用外部数据，保持其原始结构
    # 外部数据格式：
    # {
    #   "source_file": "...",
    #   "document_type": "B",
    #   "total_pages": 1,
    #   "total_rows": 35,
    #   "sessions": 1,
    #   "pages": [...]
    # }
    
    # Remove the 'transactions' list (generated by internal parser) to strictly follow external data format if present
    # User requirement: "Replace the transaction part... compatible with split json... do not add extra fields"
    if "transactions" in output_data["structured_data"]["account_summary"]:
        del output_data["structured_data"]["account_summary"]["transactions"]

    # 将外部的transaction data直接放入
    output_data["structured_data"]["account_summary"]["transaction_details"] = {
        "source_file": external_data.get("source_file", ""),
        "document_type": external_data.get("document_type", ""),
        "total_pages": external_data.get("total_pages", 0),
        "total_rows": external_data.get("total_rows", 0),
        "sessions": external_data.get("sessions", 0),
        "pages": external_data.get("pages", [])
    }
    
    return output_data


def validate_external_transaction_format(external_data: Dict[str, Any]) -> bool:
    """
    验证外部流水明细数据格式是否正确。
    
    Args:
        external_data: 外部流水明细数据
        
    Returns:
        True if valid, False otherwise
    """
    required_fields = ["pages"]
    
    for field in required_fields:
        if field not in external_data:
            print(f"Warning: Missing required field '{field}' in external transaction data")
            return False
    
    # 验证pages结构
    pages = external_data.get("pages", [])
    if not isinstance(pages, list):
        print("Warning: 'pages' should be a list")
        return False
    
    for page in pages:
        if "rows" not in page:
            print(f"Warning: Missing 'rows' in page data")
            return False
    
    return True
